// <auto-generated />
namespace DataflowICB.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class deleteuselesspropinSensor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteuselesspropinSensor));
        
        string IMigrationMetadata.Id
        {
            get { return "201711071503171_delete useless prop in Sensor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
